### ISSUE TITLE
Network error doesn't contain a status code.

### ISSUE THREAD

**Issue by ToddHoff** [jamesrochabrun/SwiftOpenAI#60]
Hi,

The doc says:

How to get the status code of network errors
You may want to build UI around the type of error that the API returns. For example, a 429 means that your requests are being rate limited. The APIError type has a case responseUnsuccessful with two associated values: a description and statusCode. Here is a usage example using the chat completion API:

```
let service = OpenAIServiceFactory.service(apiKey: apiKey)
let parameters = ChatCompletionParameters(messages: [.init(role: .user, content: .text("hello world"))],
                                          model: .gpt4o)
do {
   let choices = try await service.startChat(parameters: parameters).choices
   // Work with choices
} catch APIError.responseUnsuccessful(let description, let statusCode) {
   print("Network error with status code: \(statusCode) and description: \(description)")
} catch {
   print(error.localizedDescription)
}
```

But in reality, the status code is not available:

```
public enum APIError: Error {
   
   case requestFailed(description: String)
   case responseUnsuccessful(description: String)
   case invalidData
   case jsonDecodingFailure(description: String)
   case dataCouldNotBeReadMissingData(description: String)
   case bothDecodingStrategiesFailed
   case timeOutError
   
   public var displayDescription: String {
      switch self {
      case .requestFailed(let description): return description
      case .responseUnsuccessful(let description): return description
      case .invalidData: return "Invalid data"
      case .jsonDecodingFailure(let description): return description
      case .dataCouldNotBeReadMissingData(let description): return description
      case .bothDecodingStrategiesFailed: return "Decoding strategies failed."
      case .timeOutError: return "Time Out Error."
      }
   }

```
Just FYI.

thanks

**Comment by lzell** [comment]
Hi there,

The response status code is available here (note the second argument to `responseUnsuccessful`)
https://github.com/jamesrochabrun/SwiftOpenAI/blob/main/Sources/OpenAI/Public/Service/OpenAIService.swift#L15

I do have a theory about why you are seeing an outdated version of the code though. I have noticed that Xcode is not defaulting people to the most recent release. It seems to be a bug in the way that packages are being added.

If you tap on your project in the project tree, then tap `Package Dependencies`, what do you see there? My guess is that it defaulted you to a top version of 2.0, which is quite annoying. Please let me know what you see.

**Comment by ToddHoff** [comment]
Yep, that's exactly what I see. What is the correct version?


thanks

**Comment by lzell** [comment]
The most recent release is 3.6, which you can find here: 
https://github.com/jamesrochabrun/SwiftOpenAI/releases

@jamesrochabrun, it may be better with Apple's versioning system to always include the `patch` version when you cut a release. E.g. `3.6.0` instead of `3.6`. I'm not positive it will help, just speculating.

@ToddHoff I have found that when I add a package in Xcode I sometimes need to tab away from the version input field before the upper bound will change. So, for example, I'll put 3.6 in the lower bound and tab away and wait a second. Sometimes the upper bound unsticks. It seems finicky (good old Xcode). After a couple times of doing this, the upper bound seems to magically unstick from the default of 2.0. Another possibility is you change the version dropdown to "branch" and then select "main". This will keep you on the bleeding edge, if you are comfortable with it.

**Comment by ToddHoff** [comment]
That worked, thank you. I was able to set it to 3.6, though I agree, it's
finicky sometimes. Maybe just a note in the README?

**Comment by jamesrochabrun** [comment]
Very interesting @lzell ok lets try adding the patch from now on!

**Comment by lzell** [comment]
I added a note here into a larger PR: https://github.com/jamesrochabrun/SwiftOpenAI/pull/63#discussion_r1685546396

James let me know if you'd like me to commit it separately, happy to do that too.
